%YAML 1.1
---
# You can override all these settings the following file (for easier version control)
user_config: user_config.yaml
telegram:
  token:  # REQUIRED! obtain from @BotFather (https://telegram.me/BotFather)
  admin: []  # List of Telegram IDs that are allowed to use admin commands
  timeout: 5
imgur:
  client_id:  # REQUIRED! obtain https://api.imgur.com/oauth2/addclient
  client_secret:  # REQUIRED!
  refresh_token:  # REQUIRED! obtain via authenticate_imgur.py
  album:
  timestamp_format:
storage:
  directory: $temp/codetalkirc  # $temp variable is available, relative paths are valid
  delete_images: false
  database: images.db
  user_database: users.json
irc:
  nick: TelegramBot  # REQUIRED!
  host: irc.codetalk.io  # REQUIRED!
  port: 6667  # REQUIRED!
  #ssl: true  # currently unsupported
  channel: '#lobby'  # REQUIRED!
  timeout: 7
  auth_timeout: 5:00
logging:
  active: true
  path: errors.log
  level: INFO
...
